In [1]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
age = np.array([24, 28,36,42, 60])
age

array([24, 28, 36, 42, 60])

In [4]:
age.ndim

1

In [5]:
type(age)

numpy.ndarray

In [6]:
age = np.array([[24], [28],[36],[42], [60]])
age

array([[24],
       [28],
       [36],
       [42],
       [60]])

In [7]:
data = np.array([[24,174,74,90], [28,170,76,100],[36,168,70,95],[42,166,80,99], [60,170,86,110]])
data

array([[ 24, 174,  74,  90],
       [ 28, 170,  76, 100],
       [ 36, 168,  70,  95],
       [ 42, 166,  80,  99],
       [ 60, 170,  86, 110]])

In [8]:
data.shape

(5, 4)

In [9]:
data.ndim

2

In [24]:
type(data)

numpy.ndarray

In [10]:
# how we access the coloumn
#      row,columns
#      start:end-1 , start:end-1
data[:,0:1]  # accessing column

array([[24],
       [28],
       [36],
       [42],
       [60]])

In [11]:
data[0:1,:]  # accessing row

array([[ 24, 174,  74,  90]])

In [12]:
print("Mean: " , np.mean(data[:,0:1]))
print("Median: " , np.median(data[:,0:1]))
print("standard deviation: " , np.std(data[:,0:1]))
print("standard deviation with rounding: " , np.round(np.std(data[:,0:1]),2))
print("variance: " , np.var(data[:,0:1]))
print("Min: " , np.min(data[:,0:1]))
print("Max: " , np.max(data[:,0:1]))
print("25th percentile: " , np.percentile(data[:,0:1],25))
print("50th percentile: " , np.percentile(data[:,0:1],50))
print("75th percentile: " , np.percentile(data[:,0:1],75))

Mean:  38.0
Median:  36.0
standard deviation:  12.649110640673518
standard deviation with rounding:  12.65
variance:  160.0
Min:  24
Max:  60
25th percentile:  28.0
50th percentile:  36.0
75th percentile:  42.0

In [13]:
z1 = np.random.randint(10,99,1) # any two digit number
z1

array([75], dtype=int32)

In [14]:
z2 = np.random.randint(1000,9999,1) # any 4 digit number
z2

array([3965], dtype=int32)

In [15]:
z3 = np.random.randint(10,99,10) # 10 different values can be generated
z3

array([68, 74, 60, 50, 60, 85, 23, 96, 84, 89], dtype=int32)

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame(data)
df

    0    1   2    3
0  24  174  74   90
1  28  170  76  100
2  36  168  70   95
3  42  166  80   99
4  60  170  86  110

In [23]:
type(df)

pandas.core.frame.DataFrame

In [18]:
names = ["Age","Height","Weight","BP"]

In [19]:
df.columns = names
df

   Age  Height  Weight   BP
0   24     174      74   90
1   28     170      76  100
2   36     168      70   95
3   42     166      80   99
4   60     170      86  110

In [20]:
print("min:",df["Height"].min())
print("max:",df["Height"].max())
print("mean:",df["Height"].mean())
print("median:",df["Height"].median())
print("mode:",df["Height"].mode())
print("std:",df["Height"].std())
print("var:",df["Height"].var())

min: 166
max: 174
mean: 169.6
median: 170.0
mode: 0    170
Name: Height, dtype: int64
std: 2.966479394838265
var: 8.799999999999999

In [21]:
df["Height"].describe()

count      5.000000
mean     169.600000
std        2.966479
min      166.000000
25%      168.000000
50%      170.000000
75%      170.000000
max      174.000000
Name: Height, dtype: float64

In [22]:
df[['Age',"BP"]].describe()

             Age          BP
count   5.000000    5.000000
mean   38.000000   98.800000
std    14.142136    7.395945
min    24.000000   90.000000
25%    28.000000   95.000000
50%    36.000000   99.000000
75%    42.000000  100.000000
max    60.000000  110.000000