In [1]:
import pandas as pd
df = pd.read_csv("advertising.csv")
df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,27-03-2016 00:53,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,04-04-2016 01:39,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,13-03-2016 20:35,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,10-01-2016 02:31,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,03-06-2016 03:36,0

In [ ]:
X_cont = df.iloc[:,0:4]

In [ ]:
# stndardization
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
SS_X = SS.fit_transform(X_cont)
SS_X = pd.DataFrame(SS_X)
SS_X.columns = list(X_cont)
SS_X.head()

   Daily Time Spent on Site       Age  Area Income  Daily Internet Usage
0                  0.249267 -0.114905     0.509691              1.734030
1                  0.961132 -0.570425     1.002530              0.313805
2                  0.282083 -1.139826     0.356949              1.287589
3                  0.577432 -0.798185    -0.014456              1.501580
4                  0.212664 -0.114905     1.408868              1.038731

In [ ]:
Y = df["Clicked on Ad"]

X = pd.concat([SS_X,df['Male']],axis=1)
X.head()

   Daily Time Spent on Site       Age  Area Income  Daily Internet Usage  Male
0                  0.249267 -0.114905     0.509691              1.734030     0
1                  0.961132 -0.570425     1.002530              0.313805     1
2                  0.282083 -1.139826     0.356949              1.287589     0
3                  0.577432 -0.798185    -0.014456              1.501580     1
4                  0.212664 -0.114905     1.408868              1.038731     0

In [ ]:
# data partition
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,train_size=0.7)

In [ ]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((700, 5), (300, 5), (700,), (300,))

In [ ]:
# trianing the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train,Y_train)

Y_pred_train = model.predict(X_train)
Y_pred_test = model.predict(X_test)

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score

training_score = accuracy_score(Y_train,Y_pred_train)
print("Training Accuracy score: ", np.round(training_score,2))
test_score = accuracy_score(Y_test,Y_pred_test)
print("Test Accuracy score: ", np.round(test_score,2))

Training Accuracy score:  0.97
Test Accuracy score:  0.96

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear')

In [ ]:
from sklearn.model_selection import ShuffleSplit, cross_validate
shuffle_split = ShuffleSplit(n_splits=100, test_size=0.2)

cv_results = cross_validate(model, X, Y, cv=shuffle_split, scoring = 'accuracy', return_train_score=True)

In [ ]:
import numpy as np
print("Training Accuracy score: ", np.round(np.mean(cv_results['train_score']),2))
print("Test Accuracy score: ", np.round(np.mean(cv_results['test_score']),2))

Training Accuracy score:  0.97
Test Accuracy score:  0.97

In [5]:
from sklearn.model_selection import KFold, cross_validate
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Re-define X and Y to ensure they are available in this cell's scope
X_cont = df.iloc[:,0:4]
SS = StandardScaler()
SS_X = SS.fit_transform(X_cont)
SS_X = pd.DataFrame(SS_X)
SS_X.columns = list(X_cont)
Y = df["Clicked on Ad"]
X = pd.concat([SS_X,df['Male']],axis=1)

model = LogisticRegression(solver='liblinear') # Re-initialize the model
KFold = KFold(n_splits=5)

cv_results = cross_validate(model, X, Y, cv=KFold, scoring = 'accuracy', return_train_score=True)

import numpy as np
print("Training Accuracy score: ", np.round(np.mean(cv_results['train_score']),2))
print("Test Accuracy score: ", np.round(np.mean(cv_results['test_score']),2))

Training Accuracy score:  0.97
Test Accuracy score:  0.97